# Recommendation System - Assignment 
## -----------------------------------------------------------------------------------------------------------------------------

## Problem Statement :  Build a recommender system by using cosine simillarties score.

## 1. Import necessary libraries :

In [1]:
import pandas as pd
import numpy as np 
from sklearn.metrics import pairwise_distances

import warnings
warnings.filterwarnings('ignore')

## 2. Import Dataset :

In [2]:
book_data = pd.read_csv('book.csv')
book_data

,Unnamed: 0,User.ID,Book.Title,Book.Rating
0,1,276726,Classical Mythology,5
1,2,276729,Clara Callan,3
2,3,276729,Decision in Normandy,6
3,4,276736,Flu: The Story of the Great Influenza Pandemic...,8
4,5,276737,The Mummies of Urumchi,6
...,...,...,...,...
9995,9996,162121,American Fried: Adventures of a Happy Eater.,7
9996,9997,162121,Cannibal In Manhattan,9
9997,9998,162121,How to Flirt: A Practical Guide,7
9998,9999,162121,Twilight,8
9999,10000,162129,Kids Say the Darndest Things,6

## 3. Data Understanding :

In [3]:
book_data.shape

(10000, 4)

In [4]:
book_data.isna().sum()

Unnamed: 0     0
User.ID        0
Book.Title     0
Book.Rating    0
dtype: int64

In [5]:
book_data.dtypes

Unnamed: 0      int64
User.ID         int64
Book.Title     object
Book.Rating     int64
dtype: object

## 4. Data Preparation :

In [6]:
book_data.drop(labels='Unnamed: 0',axis=1,inplace=True)
book_data

      User.ID                                         Book.Title  Book.Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [7]:
book_data.dtypes

User.ID         int64
Book.Title     object
Book.Rating     int64
dtype: object

In [8]:
book_data.columns = ['user_id','book_title','book_rating']
book_data.head()

   user_id                                         book_title  book_rating
0   276726                                Classical Mythology            5
1   276729                                       Clara Callan            3
2   276729                               Decision in Normandy            6
3   276736  Flu: The Story of the Great Influenza Pandemic...            8
4   276737                             The Mummies of Urumchi            6

## 5. Cosine similarities score :

In [9]:
book_data['user_id'].nunique()

2182

In [10]:
book_data['book_title'].nunique()

9659

In [11]:
book_data['user_id'].unique()

array([276726, 276729, 276736, ..., 162113, 162121, 162129], dtype=int64)

In [12]:
cosine_pivot_table = pd.pivot_table(data = book_data,values='book_rating',index='user_id',columns='book_title',).fillna(0) 
cosine_pivot_table.index = book_data['user_id'].unique()
cosine_pivot_table.head(50)

book_title,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,"100 Great Fantasy Short, Short Stories",...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,ï¿½?ï¿½?bermorgen.
276726,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276729,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276736,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276744,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276745,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276747,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276748,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276751,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276754,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276760,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276762,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276768,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276772,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276774,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276780,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276786,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276788,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276796,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276804,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276808,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276811,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276812,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276813,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276814,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276820,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276822,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276827,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276828,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276830,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276832,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276835,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276837,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276842,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276847,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276848,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276850,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276853,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276857,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276859,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276862,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276863,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276866,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276870,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276872,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
cosine_pivot_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 7., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
cosine_ubcf = 1-pairwise_distances(X = cosine_pivot_table.values, metric = 'cosine'  )
cosine_ubcf

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [15]:
cosine_ubcf_df = pd.DataFrame(cosine_ubcf)
cosine_ubcf_df.index = book_data['user_id'].unique()
cosine_ubcf_df.columns = book_data['user_id'].unique()
cosine_ubcf_df

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,...,162085,162091,162092,162095,162103,162107,162109,162113,162121,162129
276726,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276729,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276736,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276737,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276744,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
162109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
162113,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
162121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
162129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

### Filtering  Data :

In [16]:
cosine_ubcf_df_copy = cosine_ubcf_df.copy()

In [17]:
np.fill_diagonal(a = cosine_ubcf_df_copy.to_numpy() ,val = 0 )

In [18]:
cosine_ubcf_df_copy

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,...,162085,162091,162092,162095,162103,162107,162109,162113,162121,162129
276726,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276729,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276736,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276744,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162113,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
cosine_ubcf_df_copy.idxmax()

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...
162107    276726
162109    276726
162113    161453
162121    276726
162129    276726
Length: 2182, dtype: int64

### Top 100 users

In [20]:
first_100_users = cosine_ubcf_df_copy.iloc[:100,:100]
first_100_users

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,...,277018,277023,277028,277031,277032,277036,277042,277048,277051,277052
276726,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276729,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276736,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276744,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277036,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277042,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277048,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277051,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277052,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
first_100_users.idxmax()

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...
277036    276726
277042    276726
277048    276726
277051    276726
277052    276726
Length: 100, dtype: int64

In [22]:
book_data[(book_data['user_id']==276726) | (book_data['user_id']==277048)]

     user_id                             book_title  book_rating
0     276726                    Classical Mythology            5
380   277048  Victorious Christians You Should Know            7

### Inference : 1
**Very less data to suggest any recommendation so try for any other user id.**

In [23]:
book_data[(book_data['user_id']==8) | (book_data['user_id']==9)]

      user_id                                         book_title  book_rating
2399        8                            Ancient Celtic Romances            5
2400        8  The Western way: A practical guide to the West...            5
2401        8                                              Wings            5
2402        8                                           Truckers            5
2403        8                Keepers of the Earth Teachers Guide            6
2404        8                            The Celts Activity Book            6
2405        8                                  The Art Of Celtia            7
2406        9   The Book of Kells: Selected Plates in Full Color            6

### Inference : 2

**The person with user_id -9 will be recommended with a list of books titles which are shared by user_id - 8**

In [24]:
book_data[(book_data['user_id']==277036) | (book_data['user_id']==276729)]

     user_id                                         book_title  book_rating
1     276729                                       Clara Callan            3
2     276729                               Decision in Normandy            6
370   277036                   I Spy: A Book of Picture Riddles            9
371   277036  I Spy Spooky Night: A Book of Picture Riddles ...            9
372   277036                                          Lake News           10

### Inference : 3

**The person with user_id -2776729 will be recommended with a list of books titles which are shared by user_id - 276729**

## Other metrics :

## I. Correlation Matrix :

In [25]:
corr_matrix_pivot_table = pd.pivot_table(data = book_data,values='book_rating',index='book_title',columns='user_id',).fillna(0) 
corr_matrix_pivot_table.columns = book_data['user_id'].unique()
corr_matrix_pivot_table.head(50)

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,...,162085,162091,162092,162095,162103,162107,162109,162113,162121,162129
book_title,,,,,,,,,,,,,,,,,,,,,
"Jason, Madison &amp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Other Stories;Merril;1985;McClelland &amp,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Repairing PC Drives &amp,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
01-01-00: A Novel of the Millennium,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"1,401 More Things That P*Ss Me Off",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 Commandments Of Dating,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"100 Great Fantasy Short, Short Stories",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1001 Brilliant Ways to Checkmate,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101 Bright Ideas: Esl Activities for All Ages,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101 Dalmatians,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101 Essential Tips: House Plants,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101 Telephone Jokes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101 Wacky Computer Jokes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101 Ways to Make Money at Home,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 Edward Street,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11th Hour,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13 99 Euros,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"14,000 Things to Be Happy About",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20 Jahre 40 bleiben. Jung und schï¿½?Â¶n in den besten Jahren.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20 Years of Censored News,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"20,000 Leagues Under the Sea (Wordsworth Collection)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"20,001 Names for Baby",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2001 Spanish and English Idioms/2001 Modismos Espanoles E Ingleses: 2001 Modismos Espanoles E Ingleses,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2061: Odyssey Three,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22 Indigo Place,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
250 Things You Can Do to Make Your Cat Adore You,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
253,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28 Barbary Lane : A \Tales of the City\ Omnibus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3 Bowls : Vegetarian Recipes from an American Zen Buddhist Monastery,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"3 Plays: Our Town, the Skin of Our Teeth, the Matchmaker (Perennial Classics)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30 Things Everyone Should Know How to Do Before Turning 30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30-Minute Meals,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30: Pieces of a Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
365 Easy Low-Calorie Recipes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
365 Health and Happiness Boosters,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"40 Tons Of Trouble (Women Who Dare) (Harlequin Super Romance, No 726)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"5 Novels : Alan Mendelsohn, the Boy from Mars; Slaves of Spiegel; The Last Guru; Young Adult Novel; The Snarkout Boys and the Avocado of Death",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50 Simple Things You Can Do to Save the Earth,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
500 palabras nuevas para ti / 500 Words To Grow On,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
66 Laps: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7b,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
corr_table = corr_matrix_pivot_table.corr().round(2)
corr_table

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,...,162085,162091,162092,162095,162103,162107,162109,162113,162121,162129
276726,1.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276729,-0.0,1.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276736,-0.0,-0.0,1.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276737,-0.0,-0.0,-0.0,1.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276744,-0.0,-0.0,-0.0,-0.0,1.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162107,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,1.0,-0.0,-0.0,-0.0,-0.0
162109,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,1.0,-0.0,-0.0,-0.0
162113,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,1.0,-0.0,-0.0
162121,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,1.0,-0.0
162129,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,1.0

In [27]:
np.fill_diagonal(a = corr_table.to_numpy() ,val = 0 )

In [28]:
corr_table

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,...,162085,162091,162092,162095,162103,162107,162109,162113,162121,162129
276726,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276729,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276736,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276737,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276744,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162107,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0
162109,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0
162113,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0
162121,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0
162129,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,...,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0

### Top 20 users :

In [29]:
first_20_users = corr_table.iloc[:20,:20]
first_20_users

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,276755,276760,276762,276768,276772,276774,276780,276786,276788,276796
276726,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276729,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276736,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276737,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276744,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276745,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276747,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276748,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276751,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276754,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276755,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276760,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276762,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276768,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276772,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0,-0.0
276774,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0,-0.0
276780,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0,-0.0
276786,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0,-0.0
276788,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,-0.0
276796,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0

In [30]:
first_20_users.idxmax()

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
276745    276726
276747    276726
276748    276726
276751    276726
276754    276726
276755    276726
276760    276726
276762    276726
276768    276726
276772    276726
276774    276726
276780    276726
276786    276726
276788    276726
276796    276726
dtype: int64

In [33]:
book_data[(book_data['user_id']==276788) | (book_data['user_id']==276726)]

    user_id                                       book_title  book_rating
0    276726                              Classical Mythology            5
32   276788                             Wie Barney es sieht.            8
33   276788  Der Fluch der Kaiserin. Ein Richter- Di- Roman.            7
34   276788                                Sturmzeit. Roman.           10

### Inference :

**The person with user_id -2776726 will be recommended with a list of books titles which are shared by user_id - 276788**

## II. Euclidean Distance

In [34]:
euclidean_pivot_table = pd.pivot_table(data= book_data, values='book_rating',index='user_id',columns='book_title',).fillna(0)
euclidean_pivot_table

book_title,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,"100 Great Fantasy Short, Short Stories",...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,ï¿½?ï¿½?bermorgen.
user_id,,,,,,,,,,,,,,,,,,,,,
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278846,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278851,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
278852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
euclidean_pivot_table.index = book_data['user_id'].unique()
euclidean_pivot_table

book_title,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,"100 Great Fantasy Short, Short Stories",...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,ï¿½?ï¿½?bermorgen.
276726,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276729,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276736,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276744,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162113,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
162121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
euclidean_pivot_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 7., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [37]:
euclidean_ubcf = pairwise_distances(X = euclidean_pivot_table.values ,metric='euclidean',)
euclidean_ubcf

array([[ 0.        , 16.03121954, 16.03121954, ..., 29.05167809,
        16.88194302, 22.737634  ],
       [16.03121954,  0.        ,  8.48528137, ..., 25.67099531,
        10.        , 18.22086716],
       [16.03121954,  8.48528137,  0.        , ..., 25.67099531,
        10.        , 18.22086716],
       ...,
       [29.05167809, 25.67099531, 25.67099531, ...,  0.        ,
        26.21068484, 30.31501278],
       [16.88194302, 10.        , 10.        , ..., 26.21068484,
         0.        , 18.97366596],
       [22.737634  , 18.22086716, 18.22086716, ..., 30.31501278,
        18.97366596,  0.        ]])

In [38]:
ubcf_euclidean_metric = pd.DataFrame(data =euclidean_ubcf)
ubcf_euclidean_metric.index = book_data['user_id'].unique()
ubcf_euclidean_metric.columns = book_data['user_id'].unique()
ubcf_euclidean_metric.round(2)

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,...,162085,162091,162092,162095,162103,162107,162109,162113,162121,162129
276726,0.00,16.03,16.03,17.92,17.52,17.38,18.44,16.43,16.43,20.05,...,17.92,22.83,16.88,37.85,18.49,16.88,17.38,29.05,16.88,22.74
276729,16.03,0.00,8.49,11.66,11.05,10.82,12.45,9.22,9.22,14.73,...,11.66,18.33,10.00,35.33,12.53,10.00,10.82,25.67,10.00,18.22
276736,16.03,8.49,0.00,11.66,11.05,10.82,12.45,9.22,9.22,14.73,...,11.66,18.33,10.00,35.33,12.53,10.00,10.82,25.67,10.00,18.22
276737,17.92,11.66,11.66,0.00,13.64,13.45,14.80,12.21,12.21,16.76,...,14.14,20.00,12.81,36.22,14.87,12.81,13.45,26.89,12.81,19.90
276744,17.52,11.05,11.05,13.64,0.00,12.92,14.32,11.62,11.62,16.34,...,13.64,19.65,12.25,36.03,14.39,12.25,12.92,26.63,12.25,19.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162107,16.88,10.00,10.00,12.81,12.25,12.04,13.53,10.63,10.63,15.65,...,12.81,19.08,11.31,35.72,13.60,0.00,12.04,26.21,11.31,18.97
162109,17.38,10.82,10.82,13.45,12.92,12.73,14.14,11.40,11.40,16.19,...,13.45,19.52,12.04,35.96,14.21,12.04,0.00,26.53,12.04,19.42
162113,29.05,25.67,25.67,26.89,26.63,26.53,27.24,25.92,25.92,28.35,...,26.89,30.38,26.21,42.84,27.28,26.21,26.53,0.00,26.21,30.32
162121,16.88,10.00,10.00,12.81,12.25,12.04,13.53,10.63,10.63,15.65,...,12.81,19.08,11.31,35.72,13.60,11.31,12.04,26.21,0.00,18.97
162129,22.74,18.22,18.22,19.90,19.54,19.42,20.37,18.57,18.57,21.84,...,19.90,24.41,18.97,38.83,20.42,18.97,19.42,30.32,18.97,0.00

In [49]:
last_20_users = ubcf_euclidean_metric.iloc[-20:,-20:]
last_20_users

,162030,162031,162035,162038,162044,162047,162052,162054,162063,162068,162085,162091,162092,162095,162103,162107,162109,162113,162121,162129
162030,0.000000,13.379088,13.379088,14.071247,16.703293,10.344080,12.124356,11.575837,11.090537,12.727922,14.071247,19.949937,12.727922,36.193922,14.798649,12.727922,13.379088,26.851443,12.727922,19.849433
162031,13.379088,0.000000,12.727922,13.453624,16.186414,9.486833,11.401754,10.816654,10.295630,12.041595,13.453624,19.519221,12.041595,35.958309,14.212670,12.041595,12.727922,26.532998,12.041595,19.416488
162035,13.379088,12.727922,0.000000,13.453624,16.186414,9.486833,11.401754,10.816654,10.295630,12.041595,13.453624,19.519221,12.041595,35.958309,14.212670,12.041595,12.727922,26.532998,12.041595,19.416488
162038,14.071247,13.453624,13.453624,0.000000,16.763055,10.440307,12.206556,11.661904,11.180340,12.806248,14.142136,20.000000,12.806248,36.221541,14.866069,12.806248,13.453624,26.888659,12.806248,19.899749
162044,16.703293,16.186414,16.186414,16.763055,0.000000,13.784049,15.165751,14.730920,14.352700,15.652476,16.763055,21.931712,15.652476,37.322915,17.378147,15.652476,16.186414,28.354894,15.652476,21.840330
162047,10.344080,9.486833,9.486833,10.440307,13.784049,0.000000,7.615773,6.708204,5.830952,8.544004,10.440307,17.578396,8.544004,34.942810,11.401754,8.544004,9.486833,25.139610,8.544004,17.464249
162052,12.124356,11.401754,11.401754,12.206556,15.165751,7.615773,0.000000,9.219544,8.602325,10.630146,12.206556,18.681542,10.630146,35.510562,13.038405,10.630146,11.401754,25.922963,10.630146,18.574176
162054,11.575837,10.816654,10.816654,11.661904,14.730920,6.708204,9.219544,0.000000,7.810250,10.000000,11.661904,18.330303,10.000000,35.327043,12.529964,10.000000,10.816654,25.670995,10.000000,18.220867
162063,11.090537,10.295630,10.295630,11.180340,14.352700,5.830952,8.602325,7.810250,0.000000,9.433981,11.180340,18.027756,9.433981,35.171011,12.083046,9.433981,10.295630,25.455844,9.433981,17.916473
162068,12.727922,12.041595,12.041595,12.806248,15.652476,8.544004,10.630146,10.000000,9.433981,0.000000,12.806248,19.078784,11.313708,35.721142,13.601471,11.313708,12.041595,26.210685,11.313708,18.973666
162085,14.071247,13.453624,13.453624,14.142136,16.763055,10.440307,12.206556,11.661904,11.180340,12.806248,0.000000,20.000000,12.806248,36.221541,14.866069,12.806248,13.453624,26.888659,12.806248,19.899749
162091,19.949937,19.519221,19.519221,20.000000,21.931712,17.578396,18.681542,18.330303,18.027756,19.078784,20.000000,0.000000,19.078784,38.884444,20.518285,19.078784,19.519221,30.380915,19.078784,24.413111
162092,12.727922,12.041595,12.041595,12.806248,15.652476,8.544004,10.630146,10.000000,9.433981,11.313708,12.806248,19.078784,0.000000,35.721142,13.601471,11.313708,12.041595,26.210685,11.313708,18.973666
162095,36.193922,35.958309,35.958309,36.221541,37.322915,34.942810,35.510562,35.327043,35.171011,35.721142,36.221541,38.884444,35.721142,0.000000,36.510273,35.721142,35.958309,42.836900,35.721142,38.832976
162103,14.798649,14.212670,14.212670,14.866069,17.378147,11.401754,13.038405,12.529964,12.083046,13.601471,14.866069,20.518285,13.601471,36.510273,0.000000,13.601471,14.212670,27.276363,13.601471,20.420578
162107,12.727922,12.041595,12.041595,12.806248,15.652476,8.544004,10.630146,10.000000,9.433981,11.313708,12.806248,19.078784,11.313708,35.721142,13.601471,0.000000,12.041595,26.210685,11.313708,18.973666
162109,13.379088,12.727922,12.727922,13.453624,16.186414,9.486833,11.401754,10.816654,10.295630,12.041595,13.453624,19.519221,12.041595,35.958309,14.212670,12.041595,0.000000,26.532998,12.041595,19.416488
162113,26.851443,26.532998,26.532998,26.888659,28.354894,25.139610,25.922963,25.670995,25.455844,26.210685,26.888659,30.380915,26.210685,42.836900,27.276363,26.210685,26.532998,0.000000,26.210685,30.315013
162121,12.727922,12.041595,12.041595,12.806248,15.652476,8.544004,10.630146,10.000000,9.433981,11.313708,12.806248,19.078784,11.313708,35.721142,13.601471,11.313708,12.041595,26.210685,0.000000,18.973666
162129,19.849433,19.416488,19.416488,19.899749,21.840330,17.464249,18.574176,18.220867,17.916473,18.973666,19.899749,24.413111,18.973666,38.832976,20.420578,18.973666,19.416488,30.315013,18.973666,0.000000

In [50]:
last_20_users.idxmax()

162030    162095
162031    162095
162035    162095
162038    162095
162044    162095
162047    162095
162052    162095
162054    162095
162063    162095
162068    162095
162085    162095
162091    162095
162092    162095
162095    162113
162103    162095
162107    162095
162109    162095
162113    162095
162121    162095
162129    162095
dtype: int64

In [51]:
book_data[(book_data['user_id']==162030) | (book_data['user_id']==162095)]

      user_id                                         book_title  book_rating
9726   162030                                     Sudden Fiction            8
9727   162030                                       Best Friends            8
9728   162030                     The Right Thing to Do: A Novel            7
9729   162030                  The Vision of Emma Blau : A Novel            8
9730   162030                               The Shadow of Desire            5
9731   162030                     Eating Fire and Drinking Water            7
9732   162030                                                Moo            7
9733   162030               Cows Of Our Planet (Far Side Series)            8
9734   162030              A Hero of Our Time (Penguin Classics)            7
9735   162030                                        Strip Tease            7
9736   162030                                    Things Not Seen            6
9737   162030                                          The Beach            9
9738   162030                            Shades of Jade: A Novel            8
9739   162030                                  One Small Sparrow            8
9740   162030                                   The Robber Bride            8
9741   162030                 Ain't Gonna Be the Same Fool Twice            9
9742   162030                                      A Small Place            7
9743   162030  The Friday Book: Essays and Other Nonfiction (...           10
9744   162030                                    Dance Real Slow            8
9745   162030     False Allegations (Vintage Crime/Black Lizard)            7
9981   162095                             Lempriere's Dictionary            9
9982   162095                                Eucalyptus: A Novel            9
9983   162095                               Dogless in Metchosin            8
9984   162095                       Hen's Teeth and Horse's Toes            8
9985   162095               Why We Buy : The Science Of Shopping            8

### Inference : 
**The person with user_id -162095 will be recommended with a list of books titles which are shared by user_id - 162030**

## III. Cityblock

In [53]:
cityblock_pivot_table = pd.pivot_table(data= book_data, values='book_rating',index='user_id',columns='book_title',).fillna(0)
cityblock_pivot_table

book_title,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,"100 Great Fantasy Short, Short Stories",...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,ï¿½?ï¿½?bermorgen.
user_id,,,,,,,,,,,,,,,,,,,,,
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278846,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278851,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
278852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [54]:
cityblock_pivot_table.index = book_data['user_id'].unique()
cityblock_pivot_table

book_title,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,"100 Great Fantasy Short, Short Stories",...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,ï¿½?ï¿½?bermorgen.
276726,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276729,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276736,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
276744,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162109,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162113,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
162121,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:
cityblock_pivot_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 7., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [77]:
cityblock_ubcf = pairwise_distances(X = cityblock_pivot_table.values ,metric='cityblock',)
cityblock_ubcf

array([[  0.,  45.,  45., ..., 130.,  47.,  81.],
       [ 45.,   0.,  12., ...,  97.,  14.,  48.],
       [ 45.,  12.,   0., ...,  97.,  14.,  48.],
       ...,
       [130.,  97.,  97., ...,   0.,  99., 133.],
       [ 47.,  14.,  14., ...,  99.,   0.,  50.],
       [ 81.,  48.,  48., ..., 133.,  50.,   0.]])

In [78]:
ubcf_cityblock_metric = pd.DataFrame(data =cityblock_ubcf)
ubcf_cityblock_metric.index = book_data['user_id'].unique()
ubcf_cityblock_metric.columns = book_data['user_id'].unique()
ubcf_cityblock_metric.round(2)

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,...,162085,162091,162092,162095,162103,162107,162109,162113,162121,162129
276726,0.0,45.0,45.0,49.0,55.0,48.0,60.0,46.0,46.0,58.0,...,49.0,69.0,47.0,193.0,58.0,47.0,48.0,130.0,47.0,81.0
276729,45.0,0.0,12.0,16.0,22.0,15.0,27.0,13.0,13.0,25.0,...,16.0,36.0,14.0,160.0,25.0,14.0,15.0,97.0,14.0,48.0
276736,45.0,12.0,0.0,16.0,22.0,15.0,27.0,13.0,13.0,25.0,...,16.0,36.0,14.0,160.0,25.0,14.0,15.0,97.0,14.0,48.0
276737,49.0,16.0,16.0,0.0,26.0,19.0,31.0,17.0,17.0,29.0,...,20.0,40.0,18.0,164.0,29.0,18.0,19.0,101.0,18.0,52.0
276744,55.0,22.0,22.0,26.0,0.0,25.0,37.0,23.0,23.0,35.0,...,26.0,46.0,24.0,170.0,35.0,24.0,25.0,107.0,24.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162107,47.0,14.0,14.0,18.0,24.0,17.0,29.0,15.0,15.0,27.0,...,18.0,38.0,16.0,162.0,27.0,0.0,17.0,99.0,16.0,50.0
162109,48.0,15.0,15.0,19.0,25.0,18.0,30.0,16.0,16.0,28.0,...,19.0,39.0,17.0,163.0,28.0,17.0,0.0,100.0,17.0,51.0
162113,130.0,97.0,97.0,101.0,107.0,100.0,112.0,98.0,98.0,110.0,...,101.0,121.0,99.0,245.0,110.0,99.0,100.0,0.0,99.0,133.0
162121,47.0,14.0,14.0,18.0,24.0,17.0,29.0,15.0,15.0,27.0,...,18.0,38.0,16.0,162.0,27.0,16.0,17.0,99.0,0.0,50.0
162129,81.0,48.0,48.0,52.0,58.0,51.0,63.0,49.0,49.0,61.0,...,52.0,72.0,50.0,196.0,61.0,50.0,51.0,133.0,50.0,0.0

In [79]:
first_30_users = ubcf_cityblock_metric.iloc[:30,:30]
first_30_users

,276726,276729,276736,276737,276744,276745,276747,276748,276751,276754,...,276798,276800,276804,276808,276811,276812,276813,276814,276820,276822
276726,0.0,45.0,45.0,49.0,55.0,48.0,60.0,46.0,46.0,58.0,...,49.0,44.0,44.0,47.0,44.0,49.0,46.0,44.0,43.0,55.0
276729,45.0,0.0,12.0,16.0,22.0,15.0,27.0,13.0,13.0,25.0,...,16.0,11.0,11.0,14.0,11.0,16.0,13.0,11.0,10.0,22.0
276736,45.0,12.0,0.0,16.0,22.0,15.0,27.0,13.0,13.0,25.0,...,16.0,11.0,11.0,14.0,11.0,16.0,13.0,11.0,10.0,22.0
276737,49.0,16.0,16.0,0.0,26.0,19.0,31.0,17.0,17.0,29.0,...,20.0,15.0,15.0,18.0,15.0,20.0,17.0,15.0,14.0,26.0
276744,55.0,22.0,22.0,26.0,0.0,25.0,37.0,23.0,23.0,35.0,...,26.0,21.0,21.0,24.0,21.0,26.0,23.0,21.0,20.0,32.0
276745,48.0,15.0,15.0,19.0,25.0,0.0,30.0,16.0,16.0,28.0,...,19.0,14.0,14.0,17.0,14.0,19.0,16.0,14.0,13.0,25.0
276747,60.0,27.0,27.0,31.0,37.0,30.0,0.0,28.0,28.0,40.0,...,31.0,26.0,26.0,29.0,26.0,31.0,28.0,26.0,25.0,37.0
276748,46.0,13.0,13.0,17.0,23.0,16.0,28.0,0.0,14.0,26.0,...,17.0,12.0,12.0,15.0,12.0,17.0,14.0,12.0,11.0,23.0
276751,46.0,13.0,13.0,17.0,23.0,16.0,28.0,14.0,0.0,26.0,...,17.0,12.0,12.0,15.0,12.0,17.0,14.0,12.0,11.0,23.0
276754,58.0,25.0,25.0,29.0,35.0,28.0,40.0,26.0,26.0,0.0,...,29.0,24.0,24.0,27.0,24.0,29.0,26.0,24.0,23.0,35.0
276755,47.0,14.0,14.0,18.0,24.0,17.0,29.0,15.0,15.0,27.0,...,18.0,13.0,13.0,16.0,13.0,18.0,15.0,13.0,12.0,24.0
276760,54.0,21.0,21.0,25.0,31.0,24.0,36.0,22.0,22.0,34.0,...,25.0,20.0,20.0,23.0,20.0,25.0,22.0,20.0,19.0,31.0
276762,46.0,13.0,13.0,17.0,23.0,16.0,28.0,14.0,14.0,26.0,...,17.0,12.0,12.0,15.0,12.0,17.0,14.0,12.0,11.0,23.0
276768,47.0,14.0,14.0,18.0,24.0,17.0,29.0,15.0,15.0,27.0,...,18.0,13.0,13.0,16.0,13.0,18.0,15.0,13.0,12.0,24.0
276772,48.0,15.0,15.0,19.0,25.0,18.0,30.0,16.0,16.0,28.0,...,19.0,14.0,14.0,17.0,14.0,19.0,16.0,14.0,13.0,25.0
276774,67.0,34.0,34.0,38.0,44.0,37.0,49.0,35.0,35.0,47.0,...,38.0,33.0,33.0,36.0,33.0,38.0,35.0,33.0,32.0,44.0
276780,55.0,22.0,22.0,26.0,32.0,25.0,37.0,23.0,23.0,35.0,...,26.0,21.0,21.0,24.0,21.0,26.0,23.0,21.0,20.0,32.0
276786,46.0,13.0,13.0,17.0,23.0,16.0,28.0,14.0,14.0,26.0,...,17.0,12.0,12.0,15.0,12.0,17.0,14.0,12.0,11.0,23.0
276788,46.0,13.0,13.0,17.0,23.0,16.0,28.0,14.0,14.0,26.0,...,17.0,12.0,12.0,15.0,12.0,17.0,14.0,12.0,11.0,23.0
276796,56.0,23.0,23.0,27.0,33.0,26.0,38.0,24.0,24.0,36.0,...,27.0,22.0,22.0,25.0,22.0,27.0,24.0,22.0,21.0,33.0
276798,49.0,16.0,16.0,20.0,26.0,19.0,31.0,17.0,17.0,29.0,...,0.0,15.0,15.0,18.0,15.0,20.0,17.0,15.0,14.0,26.0
276800,44.0,11.0,11.0,15.0,21.0,14.0,26.0,12.0,12.0,24.0,...,15.0,0.0,10.0,13.0,10.0,15.0,12.0,10.0,9.0,21.0
276804,44.0,11.0,11.0,15.0,21.0,14.0,26.0,12.0,12.0,24.0,...,15.0,10.0,0.0,13.0,10.0,15.0,12.0,10.0,9.0,21.0
276808,47.0,14.0,14.0,18.0,24.0,17.0,29.0,15.0,15.0,27.0,...,18.0,13.0,13.0,0.0,13.0,18.0,15.0,13.0,12.0,24.0
276811,44.0,11.0,11.0,15.0,21.0,14.0,26.0,12.0,12.0,24.0,...,15.0,10.0,10.0,13.0,0.0,15.0,12.0,10.0,9.0,21.0
276812,49.0,16.0,16.0,20.0,26.0,19.0,31.0,17.0,17.0,29.0,...,20.0,15.0,15.0,18.0,15.0,0.0,17.0,15.0,14.0,26.0
276813,46.0,13.0,13.0,17.0,23.0,16.0,28.0,14.0,14.0,26.0,...,17.0,12.0,12.0,15.0,12.0,17.0,0.0,12.0,11.0,23.0
276814,44.0,11.0,11.0,15.0,21.0,14.0,26.0,12.0,12.0,24.0,...,15.0,10.0,10.0,13.0,10.0,15.0,12.0,0.0,9.0,21.0
276820,43.0,10.0,10.0,14.0,20.0,13.0,25.0,11.0,11.0,23.0,...,14.0,9.0,9.0,12.0,9.0,14.0,11.0,9.0,0.0,20.0
276822,55.0,22.0,22.0,26.0,32.0,25.0,37.0,23.0,23.0,35.0,...,26.0,21.0,21.0,24.0,21.0,26.0,23.0,21.0,20.0,0.0

In [81]:
first_30_users.idxmax()

276726    276774
276729    276726
276736    276726
276737    276726
276744    276726
276745    276726
276747    276726
276748    276726
276751    276726
276754    276726
276755    276726
276760    276726
276762    276726
276768    276726
276772    276726
276774    276726
276780    276726
276786    276726
276788    276726
276796    276726
276798    276726
276800    276726
276804    276726
276808    276726
276811    276726
276812    276726
276813    276726
276814    276726
276820    276726
276822    276726
dtype: int64

In [82]:
book_data[(book_data['user_id']==276822) | (book_data['user_id']==276726)]

    user_id                                         book_title  book_rating
0    276726                                Classical Mythology            5
55   276822                                  Pacific Northwest           10
56   276822                         A Soldier of the Great War            9
57   276822                                 Getting Well Again           10
58   276822                       Northwest Wines and Wineries            9
59   276822        An Atmosphere of Eternity: Stories of India            9
60   276822                                      LONESOME DOVE           10
61   276822     Shabanu: Daughter of the Wind (Border Trilogy)            6
62   276822                         Haveli (Laurel Leaf Books)            9
63   276822                                         Lieux dits            8
64   276822  The Dragons of Eden: Speculations on the Evolu...           10
65   276822                                The yawning heights            9
66   276822                                  Breathing Lessons           10
67   276822                                  The Joy Luck Club           10
68   276822          Heart of Darkness (Wordsworth Collection)            8
69   276822                                  The Angel Is Near           10

### Inference : 
**The person with user_id -276726 will be recommended with a list of books titles which are shared by user_id - 276822**

## IV. Manhattan

In [83]:
book_data_sort = book_data.sort_values('user_id')
book_data_sort

      user_id                                         book_title  book_rating
2401        8                                              Wings            5
2400        8  The Western way: A practical guide to the West...            5
2399        8                            Ancient Celtic Romances            5
2402        8                                           Truckers            5
2405        8                                  The Art Of Celtia            7
...       ...                                                ...          ...
2395   278854          La crÃ³nica del PerÃº (CrÃ³nicas de AmÃ©rica)            7
2398   278854  Celtic Mythology (Library of the World's Myths...            8
2393   278854                         A corrente de Trewis Scott            7
2394   278854                                       As valkÃ­rias            7
2397   278854     A Treasury of Irish Myth, Legend, and Folklore            6

[10000 rows x 3 columns]

In [84]:
manhattan_pivot_table = pd.pivot_table(data= book_data_sort, values='book_rating',index='user_id',columns='book_title',).fillna(0)
manhattan_pivot_table

book_title,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,"100 Great Fantasy Short, Short Stories",...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,ï¿½?ï¿½?bermorgen.
user_id,,,,,,,,,,,,,,,,,,,,,
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278846,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278851,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
278852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [85]:
manhattan_pivot_table.index = book_data_sort['user_id'].unique()
manhattan_pivot_table

book_title,"Jason, Madison &amp",Other Stories;Merril;1985;McClelland &amp,Repairing PC Drives &amp,'48,'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities,...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR,01-01-00: A Novel of the Millennium,"1,401 More Things That P*Ss Me Off",10 Commandments Of Dating,"100 Great Fantasy Short, Short Stories",...,Zora Hurston and the Chinaberry Tree (Reading Rainbow Book),\Even Monkeys Fall from Trees\ and Other Japanese Proverbs,\I Won't Learn from You\: And Other Thoughts on Creative Maladjustment,"\More More More,\ Said the Baby",\O\ Is for Outlaw,"\Surely You're Joking, Mr. Feynman!\: Adventures of a Curious Character","\Well, there's your problem\: Cartoons",iI Paradiso Degli Orchi,stardust,ï¿½?ï¿½?bermorgen.
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278846,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278849,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278851,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
278852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278854,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
manhattan_pivot_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 7., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [87]:
manhattan_ubcf = pairwise_distances(X = manhattan_pivot_table.values ,metric='manhattan',)
manhattan_ubcf

array([[  0.,  45.,  45., ..., 130.,  47.,  81.],
       [ 45.,   0.,  12., ...,  97.,  14.,  48.],
       [ 45.,  12.,   0., ...,  97.,  14.,  48.],
       ...,
       [130.,  97.,  97., ...,   0.,  99., 133.],
       [ 47.,  14.,  14., ...,  99.,   0.,  50.],
       [ 81.,  48.,  48., ..., 133.,  50.,   0.]])

In [90]:
ubcf_manhattan_metric = pd.DataFrame(data =manhattan_ubcf)
ubcf_manhattan_metric.index = book_data_sort['user_id'].unique()
ubcf_manhattan_metric.columns = book_data_sort['user_id'].unique()
ubcf_manhattan_metric.round(2)

,8,9,10,12,14,16,17,19,22,26,...,278831,278832,278836,278843,278844,278846,278849,278851,278852,278854
8,0.0,45.0,45.0,49.0,55.0,48.0,60.0,46.0,46.0,58.0,...,49.0,69.0,47.0,193.0,58.0,47.0,48.0,130.0,47.0,81.0
9,45.0,0.0,12.0,16.0,22.0,15.0,27.0,13.0,13.0,25.0,...,16.0,36.0,14.0,160.0,25.0,14.0,15.0,97.0,14.0,48.0
10,45.0,12.0,0.0,16.0,22.0,15.0,27.0,13.0,13.0,25.0,...,16.0,36.0,14.0,160.0,25.0,14.0,15.0,97.0,14.0,48.0
12,49.0,16.0,16.0,0.0,26.0,19.0,31.0,17.0,17.0,29.0,...,20.0,40.0,18.0,164.0,29.0,18.0,19.0,101.0,18.0,52.0
14,55.0,22.0,22.0,26.0,0.0,25.0,37.0,23.0,23.0,35.0,...,26.0,46.0,24.0,170.0,35.0,24.0,25.0,107.0,24.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278846,47.0,14.0,14.0,18.0,24.0,17.0,29.0,15.0,15.0,27.0,...,18.0,38.0,16.0,162.0,27.0,0.0,17.0,99.0,16.0,50.0
278849,48.0,15.0,15.0,19.0,25.0,18.0,30.0,16.0,16.0,28.0,...,19.0,39.0,17.0,163.0,28.0,17.0,0.0,100.0,17.0,51.0
278851,130.0,97.0,97.0,101.0,107.0,100.0,112.0,98.0,98.0,110.0,...,101.0,121.0,99.0,245.0,110.0,99.0,100.0,0.0,99.0,133.0
278852,47.0,14.0,14.0,18.0,24.0,17.0,29.0,15.0,15.0,27.0,...,18.0,38.0,16.0,162.0,27.0,16.0,17.0,99.0,0.0,50.0
278854,81.0,48.0,48.0,52.0,58.0,51.0,63.0,49.0,49.0,61.0,...,52.0,72.0,50.0,196.0,61.0,50.0,51.0,133.0,50.0,0.0

In [93]:
last_30_users = ubcf_manhattan_metric.iloc[-30:,-30:]
last_30_users

,278759,278760,278764,278767,278772,278773,278777,278778,278782,278786,...,278831,278832,278836,278843,278844,278846,278849,278851,278852,278854
278759,0.0,8.0,3.0,7.0,11.0,28.0,6.0,9.0,20.0,7.0,...,11.0,31.0,9.0,155.0,20.0,9.0,10.0,92.0,9.0,43.0
278760,8.0,0.0,9.0,13.0,17.0,34.0,12.0,15.0,26.0,13.0,...,17.0,37.0,15.0,161.0,26.0,15.0,16.0,98.0,15.0,49.0
278764,3.0,9.0,0.0,8.0,12.0,29.0,7.0,10.0,21.0,8.0,...,12.0,32.0,10.0,156.0,21.0,10.0,11.0,93.0,10.0,44.0
278767,7.0,13.0,8.0,0.0,16.0,33.0,11.0,14.0,25.0,12.0,...,16.0,36.0,14.0,160.0,25.0,14.0,15.0,97.0,14.0,48.0
278772,11.0,17.0,12.0,16.0,0.0,37.0,15.0,18.0,29.0,16.0,...,20.0,40.0,18.0,164.0,29.0,18.0,19.0,101.0,18.0,52.0
278773,28.0,34.0,29.0,33.0,37.0,0.0,32.0,35.0,46.0,33.0,...,37.0,57.0,35.0,181.0,46.0,35.0,36.0,118.0,35.0,69.0
278777,6.0,12.0,7.0,11.0,15.0,32.0,0.0,13.0,24.0,11.0,...,15.0,35.0,13.0,159.0,24.0,13.0,14.0,96.0,13.0,47.0
278778,9.0,15.0,10.0,14.0,18.0,35.0,13.0,0.0,27.0,14.0,...,18.0,38.0,16.0,162.0,27.0,16.0,17.0,99.0,16.0,50.0
278782,20.0,26.0,21.0,25.0,29.0,46.0,24.0,27.0,0.0,25.0,...,29.0,49.0,27.0,173.0,38.0,27.0,28.0,110.0,27.0,61.0
278786,7.0,13.0,8.0,12.0,16.0,33.0,11.0,14.0,25.0,0.0,...,16.0,36.0,14.0,160.0,25.0,14.0,15.0,97.0,14.0,48.0
278798,15.0,21.0,16.0,20.0,24.0,41.0,19.0,22.0,33.0,20.0,...,24.0,44.0,22.0,168.0,33.0,22.0,23.0,105.0,22.0,56.0
278800,10.0,16.0,11.0,15.0,19.0,36.0,14.0,17.0,28.0,15.0,...,19.0,39.0,17.0,163.0,28.0,17.0,18.0,100.0,17.0,51.0
278806,10.0,16.0,11.0,15.0,19.0,36.0,14.0,17.0,28.0,15.0,...,19.0,39.0,17.0,163.0,28.0,17.0,18.0,100.0,17.0,51.0
278807,11.0,17.0,12.0,16.0,20.0,37.0,15.0,18.0,29.0,16.0,...,20.0,40.0,18.0,164.0,29.0,18.0,19.0,101.0,18.0,52.0
278818,20.0,26.0,21.0,25.0,29.0,46.0,24.0,27.0,38.0,25.0,...,29.0,49.0,27.0,173.0,38.0,27.0,28.0,110.0,27.0,61.0
278820,4.0,10.0,5.0,9.0,13.0,30.0,8.0,11.0,22.0,9.0,...,13.0,33.0,11.0,157.0,22.0,11.0,12.0,94.0,11.0,45.0
278823,8.0,14.0,9.0,13.0,17.0,34.0,12.0,15.0,26.0,13.0,...,17.0,37.0,15.0,161.0,26.0,15.0,16.0,98.0,15.0,49.0
278824,7.0,13.0,8.0,12.0,16.0,33.0,11.0,14.0,25.0,12.0,...,16.0,36.0,14.0,160.0,25.0,14.0,15.0,97.0,14.0,48.0
278825,6.0,12.0,7.0,11.0,15.0,32.0,10.0,13.0,24.0,11.0,...,15.0,35.0,13.0,159.0,24.0,13.0,14.0,96.0,13.0,47.0
278828,9.0,15.0,10.0,14.0,18.0,35.0,13.0,16.0,27.0,14.0,...,18.0,38.0,16.0,162.0,27.0,16.0,17.0,99.0,16.0,50.0
278831,11.0,17.0,12.0,16.0,20.0,37.0,15.0,18.0,29.0,16.0,...,0.0,40.0,18.0,164.0,29.0,18.0,19.0,101.0,18.0,52.0
278832,31.0,37.0,32.0,36.0,40.0,57.0,35.0,38.0,49.0,36.0,...,40.0,0.0,38.0,184.0,49.0,38.0,39.0,121.0,38.0,72.0
278836,9.0,15.0,10.0,14.0,18.0,35.0,13.0,16.0,27.0,14.0,...,18.0,38.0,0.0,162.0,27.0,16.0,17.0,99.0,16.0,50.0
278843,155.0,161.0,156.0,160.0,164.0,181.0,159.0,162.0,173.0,160.0,...,164.0,184.0,162.0,0.0,173.0,162.0,163.0,245.0,162.0,196.0
278844,20.0,26.0,21.0,25.0,29.0,46.0,24.0,27.0,38.0,25.0,...,29.0,49.0,27.0,173.0,0.0,27.0,28.0,110.0,27.0,61.0
278846,9.0,15.0,10.0,14.0,18.0,35.0,13.0,16.0,27.0,14.0,...,18.0,38.0,16.0,162.0,27.0,0.0,17.0,99.0,16.0,50.0
278849,10.0,16.0,11.0,15.0,19.0,36.0,14.0,17.0,28.0,15.0,...,19.0,39.0,17.0,163.0,28.0,17.0,0.0,100.0,17.0,51.0
278851,92.0,98.0,93.0,97.0,101.0,118.0,96.0,99.0,110.0,97.0,...,101.0,121.0,99.0,245.0,110.0,99.0,100.0,0.0,99.0,133.0
278852,9.0,15.0,10.0,14.0,18.0,35.0,13.0,16.0,27.0,14.0,...,18.0,38.0,16.0,162.0,27.0,16.0,17.0,99.0,0.0,50.0
278854,43.0,49.0,44.0,48.0,52.0,69.0,47.0,50.0,61.0,48.0,...,52.0,72.0,50.0,196.0,61.0,50.0,51.0,133.0,50.0,0.0

In [94]:
last_30_users.idxmax()

278759    278843
278760    278843
278764    278843
278767    278843
278772    278843
278773    278843
278777    278843
278778    278843
278782    278843
278786    278843
278798    278843
278800    278843
278806    278843
278807    278843
278818    278843
278820    278843
278823    278843
278824    278843
278825    278843
278828    278843
278831    278843
278832    278843
278836    278843
278843    278851
278844    278843
278846    278843
278849    278843
278851    278843
278852    278843
278854    278843
dtype: int64

In [95]:
book_data[(book_data['user_id']==278759) | (book_data['user_id']==278843)]

      user_id                                         book_title  book_rating
2321   278759                          How to Say It Style Guide            1
2353   278843                                         The Mighty            9
2354   278843                     Adventures of Huckleberry Finn            7
2355   278843  Murder on the Orient Express (Hercule Poirot M...            8
2356   278843  The Body in the Library (Miss Marple Mysteries...            9
2357   278843                 Half Life: What We Give Up to Work            8
2358   278843  Her Pregnant Agenda : Marrying The Boss's Daug...            9
2359   278843  To Wed A Sheik   Desert Brides (Silhouette Rom...            7
2360   278843                                  WLD ACCORDNG GARP            7
2361   278843  The Magician's Nephew (The Chronicles of Narni...            8
2362   278843                                Midnight Masquerade           10
2363   278843                                          Flashback            8
2364   278843                       New Zoos (First Book Series)            8
2365   278843                                      Wedding Night            7
2366   278843                                            Othello            7
2367   278843                   You're Not a Kid Anymore When...            9
2368   278843  Stalin's Silver: The Sinking of the U.S.S. Joh...            8
2369   278843                              This Present Darkness            6
2370   278843                                  The First Counsel            7
2371   278843                       Tinker, Tailor, Soldier, Spy            5
2372   278843  The Berenstain Bears and Too Much Vacation (Fi...            7

### Inference : 
**The person with user_id -278759 will be recommended with a list of books titles which are shared by user_id - 278843**

### ------------------------------------------------------------------------------------------------------------------------------------------------------------